import SwiftUI
import AppFactoryKit
import AppFactoryKitRevenueCat

// ─────────────────────────────────────────────────────────────────────────
// SubscriptionTracker — generated by AppFactoryKit appgen from niche "subscription-tracker".
// Per-app surface = this config + ContentView's feature. Everything that earns
// (onboarding, paywall, subscriptions, funnel) is inherited from the kit.
// ─────────────────────────────────────────────────────────────────────────

// Paste your RevenueCat public SDK key here to go live. Until then the app runs
// on a mock provider so you can preview the real paywall in the simulator.
private let revenueCatKey = "appl_REPLACE_ME"

@MainActor
enum SubscriptionTrackerFactory {
    static func make() -> AppFactory {
        let provider: PurchaseProvider = revenueCatKey == "appl_REPLACE_ME"
            ? MockPurchaseProvider()
            : RevenueCatPurchaseProvider(apiKey: revenueCatKey, entitlementID: "premium")

        let config = AppFactoryConfiguration(
            appName: "SubscriptionTracker",
            purchaseProvider: provider,
            onboarding: OnboardingConfiguration(
                slides: [
                    .init(systemImage: "dollarsign.circle",
                          title: "SubscriptionTracker",
                          message: "Track recurring subs, get renewal reminders."),
                    .init(systemImage: "chart.line.uptrend.xyaxis",
                          title: "Go Pro",
                          message: "Unlimited subs, reminders, spend insights.")
                ],
                presentsPaywallOnFinish: true,
                accent: .green
            ),
            paywall: PaywallConfiguration(
                headline: "Unlock SubscriptionTracker Pro",
                subheadline: "Unlimited subs, reminders, spend insights.",
                benefits: [
                    .init(systemImage: "infinity", title: "Unlimited subs"),
                    .init(systemImage: "bolt.fill", title: "Reminders"),
                    .init(systemImage: "nosign", title: "Spend insights")
                ],
                productIDs: ["subscription-tracker_yearly", "subscription-tracker_weekly"],
                highlightedProductID: "subscription-tracker_yearly",
                ctaTitle: "Continue",
                dismissButtonDelay: 4,
                isDismissable: true,
                termsURL: URL(string: "https://YOURDOMAIN.com/terms"),
                privacyURL: URL(string: "https://YOURDOMAIN.com/privacy"),
                style: PaywallStyle(accent: .green, heroSystemImage: "dollarsign.circle")
            )
        )
        return AppFactory(config)
    }
}

@main
struct SubscriptionTrackerApp: App {
    @StateObject private var factory = SubscriptionTrackerFactory.make()

    var body: some Scene {
        WindowGroup {
            ContentView()
                .appFactoryRoot(factory)
                .tint(.green)
        }
    }
}
